= Overview
:website: https://peacetrue.github.io
:app-group: com.github.peacetrue.gradle
:app-name: peacetrue-gradle
:imagesdir: docs/antora/modules/ROOT/assets/images

image:https://img.shields.io/github/actions/workflow/status/peacetrue/{app-name}/main.yml?branch=master["GitHub Workflow Status",link="https://github.com/peacetrue/{app-name}/actions"]
image:https://snyk.io/test/github/peacetrue/{app-name}/badge.svg["Snyk",link="https://app.snyk.io/org/peacetrue"]
image:https://img.shields.io/testspace/tests/peacetrue/peacetrue:{app-name}/master["test space",link="https://peacetrue.testspace.com/"]
image:https://img.shields.io/codecov/c/github/peacetrue/{app-name}/master["Codecov",link="https://app.codecov.io/gh/peacetrue/{app-name}"]
image:https://img.shields.io/nexus/r/{app-group}/peacetrue-gradle-plugin?label=peacetrue-gradle-plugin&server=https%3A%2F%2Foss.sonatype.org%2F["peacetrue-gradle-plugin",link="https://search.maven.org/search?q=peacetrue-gradle-plugin"]

//@formatter:off
link:README.zh_CN.adoc[中文]

== Introduction

The `peacetrue-gradle-plugin` is used to configure Java projects according to conventions and automatically prepare the test environment. The conventions are as follows:

* Apply the `JavaLibraryPlugin` to all projects.
* Configure the use of `JUnitPlatform` in all projects.
* Add the test library `org.junit.jupiter:junit-jupiter-engine` in sub-projects.
* Apply the `JacocoPlugin` to sub-projects.
* If it is a multi-project repository, apply the `TestReportAggregationPlugin` and `JacocoReportAggregationPlugin` to the root project.

NOTE: A repository may contain one or more projects. If it contains only one project, the root project is considered a sub-project.

== Background

Multiple Java projects often require similar configurations. Using a plugin can help standardize these configurations.

== Prerequisites

Minimum supported versions:

* Gradle: 7.6
* Java: 1.8

== Usage

From the mavenCentral repository (real-time):

.build.gradle
[source%nowrap,gradle,subs="specialchars,attributes"]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.github.peacetrue.gradle:peacetrue-gradle-plugin:\{latest-version}"
    }
}

apply plugin: "io.github.peacetrue.gradle.build-convention"
----

From the gradlePluginPortal (delayed, subject to approval):

.build.gradle
[source%nowrap,gradle,subs="specialchars,attributes"]
----
plugins {
    id "io.github.peacetrue.gradle.build-convention" version "\{latest-version}"
}
----

Or:

.build.gradle
[source%nowrap,gradle,subs="specialchars,attributes"]
----
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.github.peacetrue.gradle:peacetrue-gradle-plugin:\{latest-version}"
    }
}

apply plugin: "io.github.peacetrue.gradle.build-convention"
----

Check the version badge at the top of the page for the latest version.

== Contributors

. peacetrue(xiayouxue@hotmail.com)

== Timeline

Initial commit on 2022-05-02, last commit on {localdate}.

== License

https://github.com/peacetrue/{app-name}/blob/master/LICENSE[Apache License 2.0^]
